##theme: jekyll-theme-minimal
remote_theme: peterdesmet/petridish@3.1
title: Samanta Orellana, PhD
description: Fungus weevils & biodiversity data
baseurl:  "/samantaorellana.github.io"

# SOCIAL PROFILES
social:
  email: samanta.orellana@ku.com
  bluesky: coleopterasam.bsky.social
  linkedin: https://www.linkedin.com/in/samanta-orellana
  github: ksorellana

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default                   # Use default.html layout by default for all files
  - scope:
      type: posts
    values:
      permalink: "/blog/:year/:slug/"   # Use /blog/yyyy/{filename}/ as permalink for all posts
