##theme: jekyll-theme-minimal
remote_theme: peterdesmet/petridish@3.1
title: Samanta Orellana, PhD
description: Fungus weevils & biodiversity data

# SOCIAL PROFILES
social:
  email: samanta.orellana@ku.com
  bluesky: https://bsky.app/profile/coleopterasam.bsky.social
  linkedin: https://www.linkedin.com/in/samanta-orellana
  github: ksorella
